// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKAmVAmfvqngAfT0T65J3TWPJ9cGBy68',
    appId: '1:906880620966:web:84952d4768aaf8ae0d5767',
    messagingSenderId: '906880620966',
    projectId: 'netrasaarthi-flutter-project',
    authDomain: 'netrasaarthi-flutter-project.firebaseapp.com',
    storageBucket: 'netrasaarthi-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmQb51o_JtdAccVt_NOQZc4kBzqZLuCM',
    appId: '1:906880620966:android:606b5de66bd9b0d00d5767',
    messagingSenderId: '906880620966',
    projectId: 'netrasaarthi-flutter-project',
    storageBucket: 'netrasaarthi-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZmpXirk1etD7HDQvoVIXS6OxcFV4v30',
    appId: '1:906880620966:ios:9830a0b16e03d86b0d5767',
    messagingSenderId: '906880620966',
    projectId: 'netrasaarthi-flutter-project',
    storageBucket: 'netrasaarthi-flutter-project.firebasestorage.app',
    iosBundleId: 'netrasaarthi.com.netrasaarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZmpXirk1etD7HDQvoVIXS6OxcFV4v30',
    appId: '1:906880620966:ios:9830a0b16e03d86b0d5767',
    messagingSenderId: '906880620966',
    projectId: 'netrasaarthi-flutter-project',
    storageBucket: 'netrasaarthi-flutter-project.firebasestorage.app',
    iosBundleId: 'netrasaarthi.com.netrasaarthi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKAmVAmfvqngAfT0T65J3TWPJ9cGBy68',
    appId: '1:906880620966:web:0d4410ed266416480d5767',
    messagingSenderId: '906880620966',
    projectId: 'netrasaarthi-flutter-project',
    authDomain: 'netrasaarthi-flutter-project.firebaseapp.com',
    storageBucket: 'netrasaarthi-flutter-project.firebasestorage.app',
  );
}
